version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
     - apt-get update
     - echo "prebuild phase"
     - ls
     - mvn -f myapp/pom.xml clean install
  post_build:
    commands:
     - ls 
